name: 'Lint NPM Package'
description: 'This action will lint a NPM package (a script named lint is required)'
runs:
  using: 'composite'
  steps: 
    - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: 🟩 Setup Node.js 10
        uses: actions/setup-node@v2
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com/
          scope: '@unosquare'
      - name: 📦 Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: 🤠 npm install
        run: npm ci
      - name: 🎠 Run Lint
        run: npm run lint
