name: 'Publish WebPart NPM Package'
description: 'This action will publish a NPM package'
inputs:
  access-token:
    description: 'GitHub Registry Package Access Token'
    required: true
    
runs:
  using: 'composite'
  steps: 
    - run: rm ./dist/package.json
      shell: bash
    - run: mv ./dist/src/* ./dist/
      shell: bash
    - run: echo "//registry.npmjs.org/:_authToken=${{ inputs.access-token }}" > ~/.npmrc
      shell: bash
    - run: export NODE_AUTH_TOKEN=${{ inputs.access-token }}; npm publish
      shell: bash
